
- name: Create config file for filebeat
  template:
    src: filebeat.yaml.j2
    owner: root
    mode: "0644"
    dest: "/data/filebeat/filebeat.yml"

- name: Create a filebeat container
  docker_container:
    name: "{{ filebeat_container_name }}"
    image: docker.elastic.co/beats/filebeat:6.3.2
    state: started
    user: root
    restart_policy: always
    networks:
      - name: "{{ docker_network.Name }}"
    volumes:
      - "/data/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/log/:/var/log/docker-host/:ro"
