- name: Create kibana container
  docker_container:
    name: "{{ kibana_container_name }}"
    image: docker.elastic.co/kibana/kibana-oss:6.3.2
    state: started
    restart_policy: always
    ports:
      - 5601:5601
    networks:
      - name: "{{ docker_network.Name }}"
