- name: Create MySQL Master container
  docker_container:
    name: "{{ mysql_master_container_name }}"
    image: actency/docker-mysql-replication:5.7
    state: started
    detach: yes
    env:
      { "MYSQL_ROOT_PASSWORD": "complexpass", "MYSQL_USER": "mysql_user", "MYSQL_PASSWORD": "alsocomplexpass", "MYSQL_DATABASE": "sample", "REPLICATION_USER": "replication_user", "REPLICATION_PASSWORD": "somewhatcomplexpass" }
    restart_policy: always
    networks:
      - name: "{{ docker_network.Name }}"
    volumes:
      - "/data/{{ mysql_master_container_name }}:/mysql/var/lib/mysql"  

- name: Create MySQL Slave container
  docker_container:
    name: "{{ mysql_slave_container_name }}"
    image: actency/docker-mysql-replication:5.7
    state: started
    detach: yes
    env:
      { "MYSQL_ROOT_PASSWORD": "complexpass", "MYSQL_USER": "mysql_user", "MYSQL_PASSWORD": "alsocomplexpass", "MYSQL_DATABASE": "sample", "REPLICATION_USER": "replication_user", "REPLICATION_PASSWORD": "somewhatcomplexpass" }
    restart_policy: always
    links:
      - "{{ mysql_master_container_name }}:master"
    networks:
      - name: "{{ docker_network.Name }}"
    volumes:
      - "/data/{{ mysql_slave_container_name }}:/mysql/var/lib/mysql"
