- name: Create a data folder for all containers
  file:
    path: "/data/{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ elasticsearch_container_name }}"
    - "{{ logstash_container_name }}/pipelines"
    - "{{ filebeat_container_name }}"
    - "{{ nginx_container_name }}/conf.d"
    - "{{ nginx_container_name }}/ssl/"
    - "{{ mysql_master_container_name }}/mysql"
    - "{{ mysql_slave_container_name }}/mysql"

- name: Create Docker Network
  docker_network:
    name: "{{ docker_network }}"
